server:
  shutdown: graceful
  port: 8080
  tomcat:
    max-keep-alive-requests: 100

giftcard:
  order:
    min-amount-cents: 2000          # R$ 20,00
    max-amount-cents: 100000        # R$ 1.000,00
    amount-multiple-cents: 100      # 1 = desligado. 100 = reais inteiros
  expiry:
    default-policy-ref: STANDARD_12M
    policies:
      STANDARD_12M: { months: 12 }
  idempotency:
    retention: P7D
    key-min-length: 16
    key-max-length: 64
    fingerprint-version: v1